/** Declaration file generated by dts-gen */

declare class SimpleCrypto {
    constructor(...args: any[]);

    decrypt(...args: any[]): void;

    decryptObject(...args: any[]): void;

    encrypt(...args: any[]): void;

    encryptObject(...args: any[]): void;

    setSecret(...args: any[]): void;

    static generateRandom(...args: any[]): void;

}


declare namespace SimpleCrypto {
    namespace prototype {
        function decrypt(...args: any[]): void;

        function decryptObject(...args: any[]): void;

        function encrypt(...args: any[]): void;

        function encryptObject(...args: any[]): void;

        function setSecret(...args: any[]): void;

    }

}

